---
- name: Install Nginx
  yum: name={{ nginx_packages }} state=present
  
- name: Install settings nginx forward jenkins
  template: src={{ config_file }} dest=/etc/nginx/conf.d/{{ site_name }} owner=root group=root mode=0644
  notify: Restart Nginx