---
- hosts: all
  become: yes

  tasks:
        - name: Install Repo Remi
          yum: name={{ item }} state=present
          with_items:
            - "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"

        - name: Install EPEL repo
          yum: name=epel-release state=present

        - name: Ensure firewalld is started (for production).
          service: name=firewalld state=started

        - name: Firewalld port 8090
          command: "firewall-cmd --add-port=8090/tcp --permanent"
        - name: Reload Rules Firewalld
          command: "firewall-cmd --reload"
        
        - name: Install Node.js and npm
          yum: name=npm state=present enablerepo=epel
        
        - name: Install Forever (to run our Node.js app).
          npm: name=forever global=yes state=present
 
        - name: Ensure Node.js app folder exists.
          file: "path={{ item.node_apps_location }} state=directory"
          with_items:
            - node_apps_location: "/root/teste/node.js"
        - name: Copy example Node.js app to server.
          copy: "src=/root/teste/node.js dest={{ item.node_apps_location }}"
          with_items:
           - node_apps_location: "/usr/local/"

        - name: Install app dependencies defined in package.json
          npm: path={{ item.node_apps_location }}/node.js
          with_items:
            - node_apps_location: "/usr/local/"

        - name: Check list of running Node.js apps.
          command: forever list
          register: forever_list
          changed_when: false

        - name: Start example Node.js app.
          command: "forever start {{ item.node_apps_location }}/node.js/app.js"
          with_items:
           - node_apps_location: "/usr/local/"

        - name: Forever Restart All
          command: "forever restartall"
