---
- hosts: all
  become: yes

  vars_files:
  - vars.yml

  pre_tasks:
  - name: Upgrade all packages.
    yum: name=* state=latest

  tasks:
  - name: Install Nginx
    yum: name={{ item }} state=present
    with_items:
        - nginx

  - name: Service start Nginx
    service: name=nginx state=started enabled=yes

  - name: Ensure Port 80/tcp on Firewalld is enabled
    command: "firewall-cmd --add-service=http --permanent"

  - name: Ensure Port 443/tcp on Firewalld is enabled
    command: "firewall-cmd --add-service=https --permanent"

  - name: Apply rules on Firewalld
    command: "firewall-cmd --reload"
