---
- hosts: all
  become: yes

  vars_files:
  - vars.yml

  pre_tasks:
  - name: Upgrade all packages.
    yum: name=* state=latest

  tasks:
  - name: Remove Apache, MariaDB and PHP 7.
    yum: name={{ item }} state=absent
    with_items:
        - httpd
        - httpd-devel
        - php70w*
        - mariadb-server

  - name: Ensure Port 80/tcp on Firewalld is disabled
    command: "firewall-cmd --remove-service=http --permanent"

  - name: Ensure Port 443/tcp on Firewalld is disabled
    command: "firewall-cmd --remove-service=https --permanent"

  - name: Apply rules on Firewalld
    command: "firewall-cmd --reload"
