# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "centos/7"
	
	config.vm.provider :libvirt do |libvirt|
		libvirt.driver = "qemu"
		libvirt.connect_via_ssh = false
		libvirt.username = "root"
		libvirt.storage_pool_name = "default"
	end

	#Application server 1.
	config.vm.define "app1" do |app|
		app.vm.hostname = "orc-app1.dev"
		app.vm.box = "centos/7"

app.vm.network :private_network, ip: "192.168.121.104"
	end

	#Application server 2.
	config.vm.define "app2" do |app|
		app.vm.hostname = "orc-app2.dev"
		app.vm.box = "centos/7"

app.vm.network :private_network, ip: "192.168.121.105"
	end

	# Database server
	config.vm.define "db" do |db|
		db.vm.hostname = "orc-db.dev"
		db.vm.box = "centos/7"

db.vm.network :private_network, ip: "192.168.121.106"
	end
end
